# Generated by Django 5.1.7 on 2026-02-13 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordSetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='transcription', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Enterprise')], max_length=20)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minutes_included', models.IntegerField(help_text='Minutes per month/user')),
                ('is_most_popular', models.BooleanField(default=False)),
                ('yearly_discount_percentage', models.IntegerField(default=20)),
            ],
            options={
                'unique_together': {('plan_type', 'billing_cycle')},
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=200)),
                ('is_included', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='accounts.plan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('mobile_number_verified', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin')], default='admin', max_length=20)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('org_id', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_attempts_count', models.IntegerField(default=0, help_text='Number of OTP verification attempts')),
                ('otp_blocked_until', models.DateTimeField(blank=True, help_text='Timestamp until which OTP sending is blocked', null=True)),
                ('is_otp_blocked', models.BooleanField(default=False, help_text='Flag indicating if user is blocked from requesting OTPs')),
                ('ai_bdr_activated', models.BooleanField(default=False, help_text='Flag indicating if AI BDR is activated')),
                ('ai_bdr_activated_date', models.DateTimeField(blank=True, help_text='Timestamp of AI BDR activation', null=True)),
                ('ai_bdr_deactivated_date', models.DateTimeField(blank=True, help_text='Timestamp of AI BDR deactivation', null=True)),
                ('transcription_activated', models.BooleanField(default=False, help_text='Flag indicating if transcription is activated')),
                ('transcription_activated_date', models.DateTimeField(blank=True, help_text='Timestamp of transcription activation', null=True)),
                ('transcription_deactivated_date', models.DateTimeField(blank=True, help_text='Timestamp of transcription deactivation', null=True)),
                ('pishing_activated', models.BooleanField(default=False, help_text='Flag indicating if pishing is activated')),
                ('pishing_activated_date', models.DateTimeField(blank=True, help_text='Timestamp of pishing activation', null=True)),
                ('pishing_deactivated_date', models.DateTimeField(blank=True, help_text='Timestamp of pishing deactivation', null=True)),
                ('ai_rec_activated', models.BooleanField(default=False, help_text='Flag indicating if AI Receptionist is activated')),
                ('ai_rec_activated_date', models.DateTimeField(blank=True, help_text='Timestamp of AI Receptionist activation', null=True)),
                ('ai_rec_deactivated_date', models.DateTimeField(blank=True, help_text='Timestamp of AI Receptionist deactivation', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
