# Generated by Django 5.1.7 on 2026-02-20 06:27
"""
Data migration: auto-create an Organization for every existing user
that doesn't already have one. Makes each existing user an 'owner' of
their own workspace so they are not disrupted after the multi-tenancy upgrade.
"""

from django.db import migrations


def create_orgs_for_existing_users(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    Organization = apps.get_model('accounts', 'Organization')

    profiles_without_org = UserProfile.objects.filter(organization__isnull=True).select_related('user')

    for profile in profiles_without_org:
        user = profile.user

        # Derive a company name: prefer existing org_name, then email domain, then username
        company_name = (
            profile.org_name
            or user.email.split('@')[0].replace('.', ' ').replace('_', ' ').title()
            or user.username
            or 'My Company'
        )

        org = Organization.objects.create(
            name=company_name,
            owner=user,
        )

        profile.organization = org
        profile.role = 'owner'
        # Sync legacy fields
        if not profile.org_name:
            profile.org_name = org.name
        if not profile.org_id:
            profile.org_id = org.customer_id
        profile.save()


def reverse_migration(apps, schema_editor):
    # On reversal, simply unlink profiles from organizations (don't delete orgs)
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.all().update(organization=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role_organization_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_orgs_for_existing_users,
            reverse_migration,
        ),
    ]
