# Generated by Django 5.1.7 on 2026-02-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitation'),
        ('rbac_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rbac_role',
            field=models.ForeignKey(blank=True, help_text='RBAC role assigned to this user within their organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='rbac_roles.role'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team this user belongs to (used for team-scoped data access).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='rbac_roles.team'),
        ),
    ]
