# Generated by Django 5.1.7 on 2026-02-25 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_rbac_role_userprofile_team'),
        ('rbac_roles', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='rbac_role',
            field=models.ForeignKey(blank=True, help_text='RBAC role to assign when the invitee joins. Defaults to Sales Rep.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='rbac_roles.role'),
        ),
    ]
