# Generated by Django 5.1.7 on 2026-02-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invitation_rbac_role'),
        ('rbac_roles', '0003_seed_admin_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='team',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams this user belongs to (supports multiple teams for cross-team collaboration).', related_name='members', to='rbac_roles.team'),
        ),
    ]
