# Generated by Django 5.1.7 on 2026-02-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_team_userprofile_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Plan name, e.g. 'Starter', 'Growth'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of this plan')),
                ('total_credits', models.PositiveIntegerField(default=1000, help_text='Total credits included in this plan (1 USD = 100 credits)')),
                ('validity_days', models.PositiveIntegerField(default=30, help_text='How many days this plan remains valid (30 = monthly, 365 = yearly)')),
                ('service_rates', models.JSONField(default=dict, help_text="Per-service credit costs. Example: {'ai_bdr_per_minute': 10}")),
                ('is_default', models.BooleanField(default=False, help_text='If True, new organizations are automatically assigned this plan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Plan',
                'verbose_name_plural': 'Credit Plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.PositiveIntegerField(default=0, help_text='Total credits allocated (copied from plan on assignment, can be overridden)')),
                ('used_credits', models.PositiveIntegerField(default=0, help_text='Credits consumed so far')),
                ('validity_till', models.DateField(blank=True, help_text='Date until which this credit allocation is valid', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='accounts.organization')),
                ('plan', models.ForeignKey(blank=True, help_text='The credit plan assigned to this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_accounts', to='accounts.creditplan')),
            ],
            options={
                'verbose_name': 'Organization Credit Account',
                'verbose_name_plural': 'Organization Credit Accounts',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, help_text="Service key, e.g. 'ai_bdr', 'ai_receptionist', 'lead_enrichment_email'", max_length=100)),
                ('action', models.CharField(choices=[('deduct', 'Deduction'), ('add', 'Addition'), ('adjustment', 'Manual Adjustment')], default='deduct', max_length=20)),
                ('credits', models.IntegerField(help_text='Credits changed. Negative for deductions, positive for additions.')),
                ('reference_id', models.CharField(blank=True, help_text='Optional reference, e.g. call_id or lead_id', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.organizationcreditaccount')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
