# Generated by Django 5.1.7 on 2026-02-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_creditplan_organizationcreditaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditplan',
            name='feature_limits',
            field=models.JSONField(blank=True, default=dict, help_text="Optional per-service usage caps (for Free Plans). Example: {'ai_bdr_per_minute': 200}"),
        ),
        migrations.AddField(
            model_name='organizationcreditaccount',
            name='feature_usage',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks credit consumption per service to enforce feature_limits'),
        ),
    ]
