# Generated by Django 5.1.7 on 2026-03-17 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_signupnotificationemail_signuprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who initiated this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
