# Generated by Django 5.1.7 on 2026-03-20 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0011_credittransaction_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandGuideline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Friendly name for this brand profile (e.g. "Corporate", "Product Launch").',
                        max_length=255,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#000000",
                        help_text="Primary brand colour in hex (e.g. #d40000).",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#333333",
                        help_text="Secondary brand colour in hex.",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#ff3333",
                        help_text="Accent colour in hex.",
                        max_length=7,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Background colour in hex.",
                        max_length=7,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#0a0a0a",
                        help_text="Primary text colour in hex.",
                        max_length=7,
                    ),
                ),
                (
                    "heading_font",
                    models.CharField(
                        default="Inter",
                        help_text="Google Font name or system font for headings.",
                        max_length=100,
                    ),
                ),
                (
                    "body_font",
                    models.CharField(
                        default="Inter",
                        help_text="Google Font name or system font for body text.",
                        max_length=100,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Primary logo (for light backgrounds).",
                        null=True,
                        upload_to="proposals/brands/logos/",
                    ),
                ),
                (
                    "logo_dark",
                    models.ImageField(
                        blank=True,
                        help_text="Logo variant for dark backgrounds.",
                        null=True,
                        upload_to="proposals/brands/logos/",
                    ),
                ),
                (
                    "brand_guidelines_doc",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded PDF/DOCX brand guidelines document.",
                        null=True,
                        upload_to="proposals/brands/docs/",
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Freeform CSS overrides applied to documents using this brand.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this brand is pre-selected in the wizard for this org.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_brand_guidelines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The organisation this brand profile belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_guidelines",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Guideline",
                "verbose_name_plural": "Brand Guidelines",
                "ordering": ["-is_default", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Document title (e.g. "Partnership Proposal for ARC Care").',
                        max_length=500,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("PROPOSAL", "Proposal"),
                            ("FLYER", "Flyer"),
                            ("BROCHURE", "Brochure"),
                            ("DATASHEET", "Datasheet"),
                            ("REPORT", "Report"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="PROPOSAL",
                        help_text="Type of document.",
                        max_length=20,
                    ),
                ),
                (
                    "content_mode",
                    models.CharField(
                        choices=[
                            ("TEXT_ONLY", "Text Only"),
                            ("TEXT_AND_IMAGES", "Text + AI Images"),
                            ("TEXT_AND_UPLOADS", "Text + Upload Images"),
                        ],
                        default="TEXT_ONLY",
                        help_text="How content is generated (text-only, text+AI images, text+uploads).",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("GENERATING", "Generating"),
                            ("REVIEW", "Review"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("EXPORTED", "Exported"),
                            ("SENT", "Sent"),
                        ],
                        default="DRAFT",
                        help_text="Current lifecycle status.",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Name of the recipient (e.g. "ARC Care Solutions").',
                        max_length=255,
                    ),
                ),
                (
                    "recipient_context",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Context notes from the wizard intake about the recipient.",
                    ),
                ),
                (
                    "generated_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Final rendered HTML content of the full document.",
                    ),
                ),
                (
                    "wizard_answers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All wizard Q&A stored as JSON for regeneration/audit.",
                    ),
                ),
                (
                    "word_count",
                    models.IntegerField(
                        default=0, help_text="Approximate word count of the document."
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Document version — incremented on each regeneration.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User this document is assigned to for collaboration.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "brand_guideline",
                    models.ForeignKey(
                        blank=True,
                        help_text="Brand profile applied to this document.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="proposals.brandguideline",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this document.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The organisation this document belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals_documents",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("REFERENCE_DOC", "Reference Document"),
                            ("LOGO", "Logo"),
                            ("IMAGE", "Image"),
                            ("BRAND_GUIDE", "Brand Guide"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Type classification of this asset.",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded file.", upload_to="proposals/assets/"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original filename as uploaded by the user.",
                        max_length=500,
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Text extracted from PDF/DOCX references (used in AI prompts).",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Brief description of this asset.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The organisation this asset belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_assets",
                        to="accounts.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_proposal_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Document this asset is attached to (null = org-level reusable asset).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="proposals.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_DOCUMENT", "Full Document Generation"),
                            ("SECTION_TEXT", "Section Text Generation"),
                            ("SECTION_IMAGE", "Section Image Generation"),
                            ("SELECTION_IMAGE", "Selection Image Generation"),
                            ("INTAKE_QUESTIONS", "Intake Questions Generation"),
                        ],
                        help_text="What type of AI generation this job performs.",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Current status of this AI job.",
                        max_length=20,
                    ),
                ),
                (
                    "prompt_used",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The full prompt sent to the AI model.",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw AI response data stored as JSON.",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if the job failed.",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='The AI model name used (e.g. "claude-sonnet-4-5").',
                        max_length=100,
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0, help_text="Total tokens consumed by this AI call."
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        default=0.0,
                        help_text="Wall-clock time for the AI call in seconds.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this AI generation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_ai_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document this AI job is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_jobs",
                        to="proposals.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Job",
                "verbose_name_plural": "AI Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order within the document (0-indexed).",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("COVER", "Cover Page"),
                            ("EXECUTIVE_SUMMARY", "Executive Summary"),
                            ("SECTION", "Section"),
                            ("TABLE", "Table"),
                            ("IMAGE", "Image"),
                            ("PRICING", "Pricing"),
                            ("TIMELINE", "Timeline"),
                            ("APPENDIX", "Appendix"),
                        ],
                        default="SECTION",
                        help_text="Semantic type of this section.",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Section heading.",
                        max_length=500,
                    ),
                ),
                (
                    "content_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Editable rich HTML content for this section.",
                    ),
                ),
                (
                    "content_raw",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Original AI-generated text (for diff/reset functionality).",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="AI-generated or user-uploaded image for this section.",
                        null=True,
                        upload_to="proposals/sections/images/",
                    ),
                ),
                (
                    "image_prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Prompt used to generate the image (for regeneration).",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="If False, section is hidden in the editor and exports.",
                    ),
                ),
                (
                    "ai_generated",
                    models.BooleanField(
                        default=False,
                        help_text="True if this section was created by AI generation.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document this section belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="proposals.document",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last user who edited this section.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_proposal_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Section",
                "verbose_name_plural": "Document Sections",
                "ordering": ["document", "order"],
            },
        ),
        migrations.CreateModel(
            name="ModuleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_model_provider",
                    models.CharField(
                        choices=[
                            ("ANTHROPIC", "Anthropic (Claude)"),
                            ("OPENAI", "OpenAI (GPT)"),
                            ("GOOGLE", "Google (Gemini)"),
                        ],
                        default="ANTHROPIC",
                        help_text="AI provider for text generation.",
                        max_length=20,
                    ),
                ),
                (
                    "text_model_name",
                    models.CharField(
                        default="claude-sonnet-4-5",
                        help_text='Specific model name (e.g. "claude-sonnet-4-5", "gpt-4o").',
                        max_length=100,
                    ),
                ),
                (
                    "image_model_provider",
                    models.CharField(
                        choices=[
                            ("GOOGLE", "Google (Gemini)"),
                            ("OPENAI", "OpenAI (DALL-E)"),
                            ("STABILITY", "Stability AI"),
                        ],
                        default="GOOGLE",
                        help_text="AI provider for image generation.",
                        max_length=20,
                    ),
                ),
                (
                    "image_model_name",
                    models.CharField(
                        default="gemini-2.0-flash-exp",
                        help_text="Specific image model name.",
                        max_length=100,
                    ),
                ),
                (
                    "fallback_text_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Fallback model if the primary text model fails.",
                        max_length=100,
                    ),
                ),
                (
                    "max_tokens_per_generation",
                    models.IntegerField(
                        default=4000, help_text="Maximum tokens per AI generation call."
                    ),
                ),
                (
                    "enable_async_generation",
                    models.BooleanField(
                        default=True,
                        help_text="If True, long AI generation runs via Celery (if configured).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.OneToOneField(
                        help_text="The organisation these settings belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_settings",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Settings",
                "verbose_name_plural": "Module Settings",
            },
        ),
    ]
