# Generated by Django 5.1.7 on 2026-06-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulesettings',
            name='max_tokens_per_generation',
            field=models.IntegerField(default=8000, help_text='Maximum tokens per AI generation call.'),
        ),
        migrations.AlterField(
            model_name='modulesettings',
            name='text_model_name',
            field=models.CharField(default='claude-sonnet-4-6', help_text='Specific model name (e.g. "claude-sonnet-4-6", "gpt-4o").', max_length=100),
        ),
    ]
