"""
Django settings for asoc_core project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import sys
import io
from pathlib import Path
import os
from dotenv import load_dotenv

# Fix Windows console encoding so Django's email console backend
# can handle UTF-8 characters without UnicodeEncodeError (cp1252 issue).
if hasattr(sys.stdout, 'buffer') and sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
if hasattr(sys.stderr, 'buffer') and sys.stderr.encoding.lower() != 'utf-8':
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Add apps/ directory to Python path so bare imports (e.g. from common.*)
# work without requiring the 'apps.' prefix throughout the codebase.
APPS_DIR = str(BASE_DIR / 'apps')
if APPS_DIR not in sys.path:
    sys.path.insert(0, APPS_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pa07arjsgj-xv-p^!k(vd33_tp7aiw(+fr*7_@9d7e$$to#4h0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = [
    "bloomers-jockey-copilot.ngrok-free.dev",
    "localhost", "127.0.0.1",
    ".lhr.life",  # localhost.run wildcard
    ".vercel.app",  # Vercel deployment
    ".now.sh",      # Vercel legacy domains
]
CSRF_TRUSTED_ORIGINS = [
    "https://bloomers-jockey-copilot.ngrok-free.dev",
    "https://*.lhr.life",
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'multiselectfield',
    'widget_tweaks',
    
    # Django Allauth for authentication
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    # Agentyne ASOC Core Apps
    'common',

    # Supporting Apps
    'accounts',

    # Proposal Builder
    'proposals',

    # RBAC – Roles, Permissions, Teams, Audit Log
    'rbac_roles',

    # Lead Ingestion Module
    'lead_ingestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for django-allauth
    'accounts.middleware.OrganizationMiddleware',    # Attaches request.organization + request.org_user_ids
    'rbac_roles.middleware.RBACMiddleware',           # Attaches request.rbac_role + request.rbac_role_name
]

ROOT_URLCONF = 'asoc_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'rbac_roles.context_processors.rbac_context',  # RBAC role in every template
            ],
            'debug': DEBUG,  # Force template reloading in debug mode
        },
    },
]

WSGI_APPLICATION = 'asoc_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:////{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Testing flag (referenced by analytics and common apps)
TESTING = False

# Name prefixes for full name processing
NAME_PREFIXES = [
    "Mr.", "Mrs.", "Ms.", "Miss", "Mx.", "Dr.", "Prof.", "Eng.", "Md.",
    "PhD", "Ph.D.", "Rev.", "Fr.", "Sr.", "Sra.", "Sir", "Lady", "Hon.",
    "Capt.", "Col.", "Lt.", "Maj.", "Gen.", "Judge", "Mister", "Mme.", "Mlle."
]

# Sites framework
SITE_ID = 1

# OpenAI API Key
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# Stripe Configuration
# Removed

# ContactOut Configuration
# Removed

# CORS Configuration (for API access)
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only in development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
]

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = "/proposals/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/accounts/login/"
LOGIN_URL = '/accounts/login/'

# Allauth settings (allauth 65.x format)
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_AUTO_SIGNUP = True

# Custom allauth adapter — auto-creates Organization on signup
ACCOUNT_ADAPTER = 'accounts.adapter.CustomAccountAdapter'

# Custom signup form — adds company_name field
ACCOUNT_SIGNUP_FORM_CLASS = 'accounts.allauth_forms.CustomSignupForm'


# ── Signup Access Control ─────────────────────────────────────────────────────
# Set to False to close the public /accounts/signup/ page.
# Users can still be created by superadmins via /admin/accounts/create-user/
# or invited via the team invite system.
ALLOW_PUBLIC_SIGNUP = os.getenv('ALLOW_PUBLIC_SIGNUP', 'True') == 'True'

# ── Email / SMTP Settings ─────────────────────────────────────────────────────
# Set EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend in .env for
# real sending. Leave unset (or set to console) to print emails to terminal.
EMAIL_BACKEND     = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST        = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT        = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS     = os.getenv('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_USE_SSL     = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
# Note: EMAIL_USE_SSL and EMAIL_USE_TLS are mutually exclusive in Django.
# Port 465 (AWS SES) → EMAIL_USE_SSL=True,  EMAIL_USE_TLS=False in .env
# Port 587 (Gmail)   → EMAIL_USE_TLS=True,  EMAIL_USE_SSL=False in .env
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
_raw_from_email = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@agentyne.com')
if '<' not in _raw_from_email:
    DEFAULT_FROM_EMAIL = f"Agentyne <{_raw_from_email}>"
else:
    DEFAULT_FROM_EMAIL = _raw_from_email
# Base URL used in invite / onboarding emails — override in .env for production
SITE_BASE_URL     = os.getenv('SITE_BASE_URL', 'http://localhost:8000')

# ── AI Slide Builder Settings ─────────────────────────────────────────────────
# Removed

# ── Credit Enforcement ───────────────────────────────────────────────────────
# Removed

# ── Proposal Builder — AI API Keys ───────────────────────────────────────────
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')
GOOGLE_API_KEY    = os.getenv('GOOGLE_API_KEY', '')

# Proposals Module AI generation settings
PROPOSALS_MAX_SECTIONS = int(os.getenv('PROPOSALS_MAX_SECTIONS', '40'))
PROPOSALS_TOKENS_PER_SECTION = int(os.getenv('PROPOSALS_TOKENS_PER_SECTION', '2000'))
PROPOSALS_SECTION_SYNC_THRESHOLD = int(os.getenv('PROPOSALS_SECTION_SYNC_THRESHOLD', '8'))

# ── Celery Configurations ──────────────────────────────────────────────────────
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = DEBUG  # Execute tasks synchronously in dev so we don't need Redis running locally

# ── Celery Beat Schedule ──────────────────────────────────────────────────────
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'process-pending-leads': {
        'task': 'lead_ingestion.tasks.process_pending_leads',
        'schedule': crontab(minute='*/5'),
        'options': {'expires': 60},
    },
}


