# Generated by Django 5.1.7 on 2026-02-25 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=True, help_text='System roles are pre-seeded and cannot be renamed/deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_role', models.CharField(blank=True, max_length=100)),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('create', 'Record Created'), ('update', 'Record Updated'), ('delete', 'Record Deleted'), ('export', 'Data Exported'), ('import', 'Data Imported'), ('role_change', 'Role Changed'), ('lead_reassign', 'Lead Reassigned'), ('camp_publish', 'Campaign Published'), ('camp_pause', 'Campaign Paused'), ('camp_delete', 'Campaign Deleted'), ('agent_activate', 'Agent Activated'), ('agent_config', 'Agent Configured'), ('agent_override', 'Agent Override'), ('access_denied', 'Access Denied (403)')], max_length=30)),
                ('module', models.CharField(blank=True, choices=[('dashboard', 'Dashboard'), ('leads', 'Leads'), ('opportunities', 'Opportunities'), ('ai_agents', 'AI Agents'), ('campaigns', 'Campaigns'), ('settings', 'Settings & User Management')], max_length=30)),
                ('affected_record_id', models.CharField(blank=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Before/after values, counts, extra context.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('leads', 'Leads'), ('opportunities', 'Opportunities'), ('ai_agents', 'AI Agents'), ('campaigns', 'Campaigns'), ('settings', 'Settings & User Management')], max_length=30)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('override', 'Override (Cross-Record Edit)'), ('export', 'Export'), ('import', 'Import'), ('publish', 'Publish / Approve')], max_length=30)),
                ('scope', models.CharField(choices=[('none', 'No Access'), ('own', 'Own Records Only'), ('team', 'Team Records'), ('all', 'Company-Wide')], default='none', max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac_roles.role')),
            ],
            options={
                'ordering': ['role', 'module', 'action'],
                'unique_together': {('role', 'module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Sales Manager responsible for this team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'organization')},
            },
        ),
    ]
