# Generated by Django 5.1.7 on 2026-06-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_roles', '0003_seed_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(blank=True, choices=[('dashboard', 'Dashboard'), ('leads', 'Leads'), ('opportunities', 'Opportunities'), ('ai_agents', 'AI Agents'), ('campaigns', 'Campaigns'), ('proposals', 'Proposal Builder'), ('settings', 'Settings & User Management')], max_length=30),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('leads', 'Leads'), ('opportunities', 'Opportunities'), ('ai_agents', 'AI Agents'), ('campaigns', 'Campaigns'), ('proposals', 'Proposal Builder'), ('settings', 'Settings & User Management')], max_length=30),
        ),
    ]
