# Generated by Django 5.1.7 on 2026-06-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_credittransaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hint', models.CharField(blank=True, help_text='Hint of the origin (e.g. webhook path, upload file name)', max_length=255, null=True)),
                ('payload', models.TextField(help_text='Raw verbatim request body or row content')),
                ('content_type', models.CharField(blank=True, help_text='Content-Type of the payload (e.g. application/json, text/csv)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Processing status of the lead', max_length=20)),
                ('error_detail', models.TextField(blank=True, help_text='Detailed error message if parsing fails', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times parsing has been retried')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the raw lead was received')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when the raw lead was processed', null=True)),
                ('tenant', models.ForeignKey(help_text='The tenant associated with this raw lead', on_delete=django.db.models.deletion.CASCADE, related_name='raw_leads', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Raw Lead',
                'verbose_name_plural': 'Raw Leads',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, help_text='Extracted name of the lead', max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, help_text='Extracted and validated phone number', max_length=100, null=True)),
                ('email_address', models.CharField(blank=True, help_text='Extracted and validated email address', max_length=255, null=True)),
                ('source', models.CharField(blank=True, help_text='Extracted source (e.g. linkedin, instagram, website)', max_length=100, null=True)),
                ('predefined_action', models.CharField(blank=True, choices=[('email', 'Email'), ('bdr_call', 'BDR Call')], help_text='Action determined based on ingestion config rules', max_length=50, null=True)),
                ('confidence_note', models.TextField(blank=True, help_text='Notes on extraction confidence or flags', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the parsed lead was created')),
                ('tenant', models.ForeignKey(help_text='The tenant associated with this parsed lead', on_delete=django.db.models.deletion.CASCADE, related_name='parsed_leads', to='accounts.organization')),
                ('raw_lead', models.OneToOneField(help_text='The source RawLead for this parsed lead', on_delete=django.db.models.deletion.PROTECT, related_name='parsed_lead', to='lead_ingestion.rawlead')),
            ],
            options={
                'verbose_name': 'Parsed Lead',
                'verbose_name_plural': 'Parsed Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantIngestionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(db_index=True, help_text='Unique API Key for authentication', max_length=255, unique=True)),
                ('batch_minutes', models.PositiveIntegerField(default=10, help_text='Batch processing interval in minutes')),
                ('default_action', models.CharField(choices=[('email', 'Email'), ('bdr_call', 'BDR Call')], default='email', help_text='Default action to apply to parsed leads', max_length=50)),
                ('action_rules', models.JSONField(blank=True, default=dict, help_text='Rules mapping source (e.g. facebook) to action (e.g. bdr_call)')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if lead ingestion is active for this tenant')),
                ('tenant', models.OneToOneField(help_text='The tenant (organization) associated with this configuration', on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_config', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Tenant Ingestion Config',
                'verbose_name_plural': 'Tenant Ingestion Configs',
            },
        ),
    ]
