# Generated by Django 5.1.7 on 2026-06-15 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_credittransaction_user'),
        ('lead_ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('mobile', models.CharField(blank=True, default='', max_length=100)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', help_text='Job title', max_length=255)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('source', models.CharField(blank=True, default='', help_text='Origin source (linkedin, facebook, etc.)', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('rejected', 'Rejected'), ('disqualified', 'Disqualified')], db_index=True, default='new', max_length=20)),
                ('heat_level', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=10)),
                ('score', models.IntegerField(default=0, help_text='Lead score 0-100')),
                ('disqualified', models.BooleanField(default=False)),
                ('enriched_job_title', models.CharField(blank=True, default='', max_length=255)),
                ('enriched_location', models.CharField(blank=True, default='', max_length=255)),
                ('enriched_work_email', models.EmailField(blank=True, default='', max_length=255)),
                ('enriched_personal_email', models.EmailField(blank=True, default='', max_length=255)),
                ('enriched_phone', models.CharField(blank=True, default='', max_length=100)),
                ('enriched_company_industry', models.CharField(blank=True, default='', max_length=255)),
                ('enriched_company_size', models.CharField(blank=True, default='', max_length=100)),
                ('enriched_linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='User responsible for this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_crm_leads', to=settings.AUTH_USER_MODEL)),
                ('parsed_lead', models.OneToOneField(blank=True, help_text='The ParsedLead that created this CRM lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_lead', to='lead_ingestion.parsedlead')),
                ('tenant', models.ForeignKey(help_text='The tenant this lead belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='crm_leads', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'CRM Lead',
                'verbose_name_plural': 'CRM Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='lead_ingest_tenant__cd9345_idx'), models.Index(fields=['tenant', 'source'], name='lead_ingest_tenant__b8fad4_idx')],
            },
        ),
    ]
