# Generated by Django 5.1.7 on 2026-06-15 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_credittransaction_user'),
        ('lead_ingestion', '0002_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedlead',
            name='confidence_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='parsedlead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parsedlead',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='parsedlead',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='parsedlead',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='parsedlead',
            name='predefined_action',
            field=models.CharField(blank=True, choices=[('email', 'Email Campaign'), ('bdr_call', 'BDR Call')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='parsedlead',
            name='raw_lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parsed_lead', to='lead_ingestion.rawlead'),
        ),
        migrations.AlterField(
            model_name='parsedlead',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='parsedlead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_leads', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='rawlead',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rawlead',
            name='error_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rawlead',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawlead',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rawlead',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rawlead',
            name='source_hint',
            field=models.CharField(blank=True, default='', help_text='Hint of the origin (e.g. webhook, linkedin, meta)', max_length=50),
        ),
        migrations.AlterField(
            model_name='rawlead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='rawlead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_leads', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='tenantingestionconfig',
            name='action_rules',
            field=models.TextField(blank=True, default='', help_text='JSON mapping source (e.g. linkedin) to action (e.g. bdr_call)'),
        ),
        migrations.AlterField(
            model_name='tenantingestionconfig',
            name='api_key',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantingestionconfig',
            name='batch_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='Batch processing interval in minutes (5, 10, or 15)'),
        ),
        migrations.AlterField(
            model_name='tenantingestionconfig',
            name='default_action',
            field=models.CharField(choices=[('email', 'Email Campaign'), ('bdr_call', 'BDR Call')], default='email', help_text='Default action when no source-specific rule matches', max_length=12),
        ),
        migrations.AlterField(
            model_name='tenantingestionconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenantingestionconfig',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_config', to='accounts.organization'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
