# Generated by Django 5.1.7 on 2026-06-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_ingestion', '0003_align_to_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlead',
            name='payload_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hex digest of payload for dedup', max_length=64),
        ),
        migrations.AlterField(
            model_name='tenantingestionconfig',
            name='api_key',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
